/**
 * Layout constants + the 110-year history of six lots on the north side of
 * Vine Street between 3rd and 4th.
 *
 * Coordinate system:  +X = east, +Z = south, Y = up. 1 unit = 1 metre.
 * The camera normally looks north at the block facades.
 */

export const LAYOUT = {
  facadeZ: -9, // building frontage line
  blockDepth: 21, // buildings extend to z = facadeZ - blockDepth
  curbNorthZ: -4.6,
  curbSouthZ: 4.6,
  sidewalkSouthZ: 9.0,
  southFacadeZ: 9.0,
  southDepth: 16,
  curbHeight: 0.16,
  sidewalkY: 0.16,
  streetHalf: 4.6,
  worldHalf: 78, // road extends this far east/west
  crossWest: [-38, -28], // west cross-street x range
  crossEast: [28, 38],
  blockX: [-28, 28],
};

/** Six lots, west to east. */
export const LOT_BOUNDS = [
  { id: 'A', x0: -28, x1: -18.2, corner: 'west' },
  { id: 'B', x0: -18.2, x1: -10.4, corner: null },
  { id: 'C', x0: -10.4, x1: 2.2, corner: null },
  { id: 'D', x0: 2.2, x1: 9.6, corner: null },
  { id: 'E', x0: 9.6, x1: 19.2, corner: null },
  { id: 'F', x0: 19.2, x1: 28, corner: 'east' },
];

// ---------------------------------------------------------------------------
// Shorthand helpers so the data below stays readable
// ---------------------------------------------------------------------------
const roof = (o = {}) => ({
  waterTower: false,
  tanks: 0,
  ac: 0,
  antennas: 0,
  dishes: 0,
  solar: 0,
  garden: 0,
  holo: false,
  pad: false,
  sign: null,
  bulkhead: true,
  pigeons: 0,
  vents: 1,
  ...o,
});

const glass = (o = {}) => ({
  tint: 0x2b3540,
  lit: 0.25,
  blinds: 0.45,
  ac: 0,
  boarded: 0,
  bars: 0,
  curtains: 0.2,
  flowerBox: 0,
  ...o,
});

// ---------------------------------------------------------------------------
// LOT A — the survivor. 1912 stone-and-brick corner bank.
// ---------------------------------------------------------------------------
const A = {
  '1945': {
    kind: 'building',
    label: 'First Fidelity Bank — built 1912',
    floors: 4,
    floorH: 3.9,
    groundH: 6.2,
    facade: { tex: 'stone', color: 0xbdb2a0, trim: 0xd6cfc0, base: 'granite', grime: 0.34 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x2a3038, lit: 0.18, blinds: 0.6, curtains: 0.1 }),
    cornice: 'heavy',
    pilasters: true,
    quoins: true,
    clock: true,
    flag: 'bunting',
    fireEscape: false,
    roof: roof({ waterTower: true, tanks: 1, antennas: 1, vents: 2, pigeons: 3 }),
    storefronts: [
      {
        name: 'FIRST FIDELITY',
        sub: 'BANK  •  TRUST  •  SAVINGS',
        type: 'bank',
        signKind: 'gilded',
        awning: null,
        color: 0x1d2b22,
        accent: 0xc9a227,
        extras: ['brassRail', 'nightDeposit', 'columns'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'painted',
      side: 'west',
      text: 'DRINK\nCOLA',
      sub: 'ICE  COLD  5¢',
      bg: 0x9e2b2b,
      fg: 0xf2e6d0,
      wear: 0.25,
    },
  },
  '1965': {
    kind: 'building',
    label: 'First Fidelity Savings — 1961 ground-floor remodel',
    floors: 4,
    floorH: 3.9,
    groundH: 6.2,
    facade: { tex: 'stone', color: 0xc4bcac, trim: 0xd8d2c4, base: 'panel', grime: 0.16 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x33414d, lit: 0.3, blinds: 0.7, curtains: 0.05 }),
    cornice: 'heavy',
    pilasters: true,
    quoins: true,
    clock: true,
    flag: 'usa',
    roof: roof({ waterTower: true, tanks: 1, antennas: 3, vents: 2, ac: 1 }),
    storefronts: [
      {
        name: 'FIRST FIDELITY',
        sub: 'SAVINGS & LOAN',
        type: 'bank',
        signKind: 'enamel',
        awning: null,
        color: 0x1f3f6b,
        accent: 0xe8e2d2,
        extras: ['aluminumMullions', 'starburst', 'nightDeposit'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'ghost',
      side: 'west',
      text: 'DRINK\nCOLA',
      sub: 'ICE  COLD  5¢',
      bg: 0x9e2b2b,
      fg: 0xf2e6d0,
      wear: 0.72,
    },
  },
  '1985': {
    kind: 'building',
    label: 'Ex-bank — cheque cashing at street level',
    floors: 4,
    floorH: 3.9,
    groundH: 6.2,
    facade: { tex: 'stone', color: 0x9a9182, trim: 0xa8a094, base: 'panel', grime: 0.78 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x22262c, lit: 0.35, blinds: 0.5, ac: 0.45, boarded: 0.12, bars: 0.3 }),
    cornice: 'heavy',
    pilasters: true,
    quoins: true,
    clock: 'broken',
    roof: roof({ waterTower: true, tanks: 1, antennas: 2, dishes: 1, ac: 2, vents: 3 }),
    storefronts: [
      {
        name: 'CASH NOW',
        sub: 'CHECKS  •  GOLD  •  LOANS',
        type: 'checkCash',
        signKind: 'neon',
        awning: null,
        color: 0x2a1f2e,
        accent: 0xffe14d,
        extras: ['securityGrille', 'barredWindow', 'atmOld'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'graffiti',
      side: 'west',
      text: 'ZEPH',
      sub: 'CREW 85',
      bg: 0x8f8677,
      fg: 0xff3d7f,
      wear: 0.4,
    },
  },
  '2005': {
    kind: 'building',
    label: 'Landmarked shell — restoration scaffolding',
    floors: 4,
    floorH: 3.9,
    groundH: 6.2,
    facade: { tex: 'stone', color: 0xb3aa9a, trim: 0xc6bfb0, base: 'granite', grime: 0.4 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x2f3944, lit: 0.4, blinds: 0.55, ac: 0.15 }),
    cornice: 'heavy',
    pilasters: true,
    quoins: true,
    clock: true,
    scaffold: true,
    roof: roof({ waterTower: true, tanks: 1, antennas: 1, dishes: 2, ac: 3, vents: 3 }),
    storefronts: [
      {
        name: 'CITY BANK',
        sub: '24 HOUR ATM',
        type: 'bank',
        signKind: 'vinyl',
        awning: 'metal',
        color: 0x123a6b,
        accent: 0xffffff,
        extras: ['atm', 'bollards'],
        width: 1.0,
      },
    ],
    wallSign: null,
  },
  '2025': {
    kind: 'building',
    label: 'Restored 1912 bank — cafe tenancy',
    floors: 4,
    floorH: 3.9,
    groundH: 6.2,
    facade: { tex: 'stone', color: 0xcdc4b2, trim: 0xe0d9ca, base: 'granite', grime: 0.14 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x384454, lit: 0.55, blinds: 0.3, flowerBox: 0.3 }),
    cornice: 'heavy',
    pilasters: true,
    quoins: true,
    clock: true,
    uplight: true,
    roof: roof({ waterTower: true, tanks: 1, ac: 2, solar: 3, garden: 4, vents: 2 }),
    storefronts: [
      {
        name: 'MATCHA & CO',
        sub: 'SLOW BAR  •  PASTRY',
        type: 'cafe',
        signKind: 'minimal',
        awning: 'canvas-flat',
        color: 0x14261f,
        accent: 0x8fd6a0,
        extras: ['sidewalkTables', 'planterRow', 'stringLights', 'sandwichBoard'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'mural',
      side: 'west',
      text: 'VINE ST',
      sub: 'EST. 1888',
      bg: 0x1d3f5c,
      fg: 0x7fe3c0,
      wear: 0.1,
    },
  },
  '2055': {
    kind: 'building',
    label: 'Heritage shell + 2049 glass cap',
    floors: 4,
    floorH: 3.9,
    groundH: 6.2,
    facade: { tex: 'stone', color: 0xb9b3a6, trim: 0xd2ccc0, base: 'granite', grime: 0.2 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x28324a, lit: 0.6, blinds: 0.15 }),
    cornice: 'heavy',
    pilasters: true,
    quoins: true,
    clock: 'digital',
    uplight: true,
    addition: { floors: 2, style: 'glass', inset: 1.4, tint: 0x6e86c8 },
    roof: roof({ waterTower: 'restored', tanks: 0, solar: 4, garden: 6, holo: true, vents: 1 }),
    storefronts: [
      {
        name: 'NEURO CAFÉ',
        sub: 'CALM  •  FOCUS  •  DECAF',
        type: 'cafeFuture',
        signKind: 'holo',
        awning: 'glow',
        color: 0x101728,
        accent: 0x7cf7ff,
        extras: ['podSeats', 'planterRow', 'holoMenu'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'holo',
      side: 'west',
      text: 'HERITAGE',
      sub: 'STRUCTURE 1912 — PROTECTED',
      bg: 0x0a1030,
      fg: 0x9fd8ff,
      wear: 0,
    },
  },
};

// ---------------------------------------------------------------------------
// LOT B — three-storey brick, endlessly re-tenanted
// ---------------------------------------------------------------------------
const B = {
  '1945': {
    kind: 'building',
    label: "Kessler Block (1901) — Vine St Luncheonette",
    floors: 3,
    floorH: 3.5,
    groundH: 4.6,
    facade: { tex: 'brick', color: 0x8e4c3a, trim: 0xc9bda6, base: 'brick', grime: 0.42 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x2b2f36, lit: 0.22, blinds: 0.35, curtains: 0.55, flowerBox: 0.2 }),
    cornice: 'simple',
    fireEscape: true,
    roof: roof({ tanks: 1, antennas: 1, vents: 2, pigeons: 2 }),
    storefronts: [
      {
        name: 'LUNCHEONETTE',
        sub: 'SANDWICHES  •  MALTEDS  •  COFFEE 5¢',
        type: 'diner',
        signKind: 'painted',
        awning: 'canvas-stripe',
        color: 0x14372c,
        accent: 0xe8dcc0,
        extras: ['stools', 'milkCrates', 'sandwichBoard', 'sidewalkClock'],
        width: 1.0,
      },
    ],
    wallSign: null,
  },
  '1965': {
    kind: 'building',
    label: 'Kessler Block — Rexall drug store',
    floors: 3,
    floorH: 3.5,
    groundH: 4.6,
    facade: { tex: 'brick', color: 0x97553f, trim: 0xd3c8b2, base: 'brick', grime: 0.3 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x36404c, lit: 0.32, blinds: 0.5, curtains: 0.3 }),
    cornice: 'simple',
    fireEscape: true,
    roof: roof({ tanks: 1, antennas: 3, vents: 2, ac: 1 }),
    storefronts: [
      {
        name: 'DRUG STORE',
        sub: 'PRESCRIPTIONS  •  SODA FOUNTAIN',
        type: 'pharmacy',
        signKind: 'plastic',
        awning: 'metal',
        color: 0x1a3f8c,
        accent: 0xff8b2e,
        extras: ['neonScript', 'gumballMachine', 'newsRack'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'painted',
      side: 'front-upper',
      text: 'SMOKE\nLUCKY',
      sub: "IT'S TOASTED",
      bg: 0x2c6b4f,
      fg: 0xf5ead2,
      wear: 0.3,
    },
  },
  '1985': {
    kind: 'building',
    label: 'Kessler Block — Video 2000',
    floors: 3,
    floorH: 3.5,
    groundH: 4.6,
    facade: { tex: 'brick', color: 0x6f4232, trim: 0x9c9384, base: 'brick', grime: 0.82 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x1e2228, lit: 0.4, blinds: 0.4, ac: 0.6, bars: 0.4, boarded: 0.15 }),
    cornice: 'simple',
    fireEscape: true,
    roof: roof({ tanks: 1, antennas: 2, dishes: 1, ac: 2, vents: 3 }),
    storefronts: [
      {
        name: 'VIDEO 2000',
        sub: 'VHS  •  BETA  •  NINTENDO',
        type: 'video',
        signKind: 'neon',
        awning: null,
        color: 0x191233,
        accent: 0xff2f92,
        extras: ['posterWall', 'securityGrille', 'newsBoxes', 'graffitiTag'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'billboard',
      side: 'front-upper',
      text: 'RENT 2\nGET 1',
      sub: 'BE KIND — REWIND',
      bg: 0x241a44,
      fg: 0x51e0ff,
      wear: 0.2,
    },
  },
  '2005': {
    kind: 'building',
    label: 'Kessler Block — mobile phone dealer',
    floors: 3,
    floorH: 3.5,
    groundH: 4.6,
    facade: { tex: 'brick', color: 0x7d4d3c, trim: 0xa9a091, base: 'brick', grime: 0.5 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x2c343d, lit: 0.45, blinds: 0.45, ac: 0.35 }),
    cornice: 'simple',
    fireEscape: true,
    roof: roof({ tanks: 1, antennas: 1, dishes: 2, ac: 3, vents: 2 }),
    storefronts: [
      {
        name: 'MOBILE ZONE',
        sub: 'FREE PHONE WITH 2-YR PLAN',
        type: 'phoneShop',
        signKind: 'vinyl',
        awning: null,
        color: 0xe8ebee,
        accent: 0x0a63c9,
        extras: ['windowDecals', 'aFrameSign', 'binPair'],
        width: 1.0,
      },
    ],
    wallSign: null,
  },
  '2025': {
    kind: 'building',
    label: 'Kessler Block — exposed brick bakery',
    floors: 3,
    floorH: 3.5,
    groundH: 4.6,
    facade: { tex: 'brick', color: 0x8b5340, trim: 0xbdb4a4, base: 'brick', grime: 0.28 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x38434f, lit: 0.6, blinds: 0.25, flowerBox: 0.4, curtains: 0.1 }),
    cornice: 'simple',
    fireEscape: true,
    roof: roof({ tanks: 1, ac: 2, solar: 2, garden: 3, vents: 2 }),
    storefronts: [
      {
        name: 'LEAVEN',
        sub: 'SOURDOUGH  •  NATURAL WINE',
        type: 'bakery',
        signKind: 'minimal',
        awning: 'canvas-flat',
        color: 0x1b1b1b,
        accent: 0xf0e2c8,
        extras: ['sidewalkTables', 'stringLights', 'bikeLeaning', 'chalkboard'],
        width: 1.0,
      },
    ],
    wallSign: null,
  },
  '2055': {
    kind: 'building',
    label: 'Kessler Block — hydroponic bar, living facade',
    floors: 3,
    floorH: 3.5,
    groundH: 4.6,
    facade: { tex: 'brick', color: 0x7a4b3c, trim: 0xa8a496, base: 'brick', grime: 0.3, living: 0.55 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x2a3550, lit: 0.65, blinds: 0.1 }),
    cornice: 'simple',
    fireEscape: 'retrofit',
    roof: roof({ tanks: 0, solar: 3, garden: 5, holo: false, pad: true, vents: 1 }),
    storefronts: [
      {
        name: 'GREENSTACK',
        sub: 'HYDROPONIC BAR  •  GROWN HERE',
        type: 'hydroponics',
        signKind: 'holo',
        awning: 'glow',
        color: 0x0d1f1a,
        accent: 0x6affc0,
        extras: ['growRacks', 'podSeats', 'holoMenu'],
        width: 1.0,
      },
    ],
    wallSign: null,
  },
};

// ---------------------------------------------------------------------------
// LOT C — vacant lot in 1945, then the Progress Building forever after
// ---------------------------------------------------------------------------
const C = {
  '1945': {
    kind: 'lot',
    label: 'Vacant lot — Kessler Bros. Cartage yard',
    fence: 'wood-hoarding',
    billboard: {
      kind: 'painted',
      w: 9.0,
      h: 3.6,
      text: 'BUY\nWAR BONDS',
      sub: 'BACK THE ATTACK  •  7th WAR LOAN',
      bg: 0x28405e,
      fg: 0xf3e4c0,
      accent: 0xc0392b,
    },
    contents: ['parkedTruck', 'crates', 'rubble', 'weeds', 'barrel', 'poster'],
    partyWall: { west: true, east: true, tex: 'brick', color: 0x7a4634, ghost: true },
  },
  '1965': {
    kind: 'building',
    label: 'The Progress Building — completed 1963',
    floors: 9,
    floorH: 3.35,
    groundH: 5.4,
    facade: {
      tex: 'spandrel',
      color: 0xd7d4cc,
      trim: 0xb9bfc4,
      base: 'travertine',
      grime: 0.1,
      mullion: 0xdadfe2,
    },
    windowStyle: 'ribbon',
    glass: glass({ tint: 0x2f5a52, lit: 0.4, blinds: 0.6, curtains: 0.05 }),
    cornice: 'parapet',
    setback: { at: 0.0, depth: 0 },
    canopy: 'modern',
    roof: roof({ tanks: 0, ac: 2, antennas: 2, vents: 3, bulkhead: true, sign: 'PROGRESS' }),
    storefronts: [
      {
        name: 'PROGRESS BUILDING',
        sub: 'OFFICES  •  SUITES 200-900',
        type: 'lobby',
        signKind: 'enamel',
        awning: null,
        color: 0x233b46,
        accent: 0xe6e9ea,
        extras: ['aluminumMullions', 'planterConcrete', 'directoryBoard'],
        width: 0.62,
      },
      {
        name: 'TRAVEL',
        sub: 'JET FLIGHTS  •  CRUISES',
        type: 'travel',
        signKind: 'plastic',
        awning: 'metal',
        color: 0x0f6fa8,
        accent: 0xffd23f,
        extras: ['posterWall', 'globeProp'],
        width: 0.38,
      },
    ],
    wallSign: null,
  },
  '1985': {
    kind: 'building',
    label: 'Progress Building — deferred maintenance',
    floors: 9,
    floorH: 3.35,
    groundH: 5.4,
    facade: {
      tex: 'spandrel',
      color: 0x9c8f74,
      trim: 0x8a8478,
      base: 'travertine',
      grime: 0.7,
      mullion: 0x8f8e88,
    },
    windowStyle: 'ribbon',
    glass: glass({ tint: 0x25423d, lit: 0.55, blinds: 0.55, ac: 0.55 }),
    cornice: 'parapet',
    canopy: 'modern',
    roof: roof({ ac: 4, antennas: 3, dishes: 2, vents: 4, sign: 'PROGRESS', bulkhead: true }),
    storefronts: [
      {
        name: 'SUITE OFFICES',
        sub: 'SPACE AVAILABLE — CALL 555-0148',
        type: 'lobby',
        signKind: 'plastic',
        awning: null,
        color: 0x2b2f33,
        accent: 0xc7c9ca,
        extras: ['planterConcrete', 'graffitiTag', 'newsBoxes'],
        width: 0.62,
      },
      {
        name: 'ARCADE',
        sub: '25¢ PLAY  •  OPEN LATE',
        type: 'arcade',
        signKind: 'neon',
        awning: null,
        color: 0x140f2b,
        accent: 0x36f0ff,
        extras: ['arcadeGlow', 'posterWall', 'graffitiTag'],
        width: 0.38,
      },
    ],
    wallSign: {
      kind: 'billboard-lit',
      side: 'front-upper',
      text: 'STEREO',
      sub: 'PORTABLE SOUND — 4 EASY PAYMENTS',
      bg: 0x1b1440,
      fg: 0xff4fa3,
      wear: 0.25,
    },
  },
  '2005': {
    kind: 'building',
    label: 'Progress Building — 2001 curtain-wall recladding',
    floors: 9,
    floorH: 3.35,
    groundH: 5.4,
    facade: {
      tex: 'curtain',
      color: 0x8fa6b0,
      trim: 0xa8b4bb,
      base: 'granite',
      grime: 0.18,
      mullion: 0xb6c0c6,
    },
    windowStyle: 'curtain',
    glass: glass({ tint: 0x2d5f6b, lit: 0.5, blinds: 0.35 }),
    cornice: 'parapet',
    canopy: 'glass',
    roof: roof({ ac: 5, antennas: 2, dishes: 3, vents: 4, bulkhead: true }),
    storefronts: [
      {
        name: 'ONE VINE',
        sub: 'COMMERCIAL TOWER',
        type: 'lobbyGlass',
        signKind: 'vinyl',
        awning: null,
        color: 0x1c2a33,
        accent: 0xdfe6ea,
        extras: ['revolvingDoor', 'planterModern', 'bollards'],
        width: 0.62,
      },
      {
        name: 'COFFEE',
        sub: 'FREE WI-FI  •  HOT SANDWICHES',
        type: 'coffeeChain',
        signKind: 'vinyl',
        awning: 'metal',
        color: 0x0d4d33,
        accent: 0xf2f2f2,
        extras: ['sidewalkTables', 'aFrameSign', 'binPair'],
        width: 0.38,
      },
    ],
    wallSign: null,
  },
  '2025': {
    kind: 'building',
    label: 'One Vine — media wall + solar shading fins',
    floors: 9,
    floorH: 3.35,
    groundH: 5.4,
    facade: {
      tex: 'curtain',
      color: 0x7f96a4,
      trim: 0x9fb0b9,
      base: 'granite',
      grime: 0.12,
      mullion: 0xc3ccd2,
      fins: true,
    },
    windowStyle: 'curtain',
    glass: glass({ tint: 0x28596b, lit: 0.62, blinds: 0.28 }),
    cornice: 'parapet',
    canopy: 'glass',
    roof: roof({ ac: 4, antennas: 1, dishes: 2, solar: 6, garden: 3, vents: 3, bulkhead: true }),
    storefronts: [
      {
        name: 'ONE VINE',
        sub: 'WORKPLACE  •  LEED PLATINUM',
        type: 'lobbyGlass',
        signKind: 'minimal',
        awning: null,
        color: 0x16232b,
        accent: 0xe8eef1,
        extras: ['revolvingDoor', 'planterModern', 'bikeRackLobby', 'evStall'],
        width: 0.62,
      },
      {
        name: 'BOWL BAR',
        sub: 'POKE  •  GRAIN  •  SMOOTHIE',
        type: 'fastCasual',
        signKind: 'minimal',
        awning: 'canvas-flat',
        color: 0x1f1a2e,
        accent: 0xffb347,
        extras: ['sidewalkTables', 'planterRow', 'deliveryBags'],
        width: 0.38,
      },
    ],
    wallSign: {
      kind: 'led',
      side: 'front-upper',
      text: 'STREAM',
      sub: 'EVERYTHING. EVERYWHERE.',
      bg: 0x081018,
      fg: 0x59e0ff,
      wear: 0,
    },
  },
  '2055': {
    kind: 'building',
    label: 'One Vine — 2041 vertical extension + living skin',
    floors: 9,
    floorH: 3.35,
    groundH: 5.4,
    facade: {
      tex: 'curtain',
      color: 0x5f6f86,
      trim: 0x7d8ea6,
      base: 'granite',
      grime: 0.14,
      mullion: 0x9fb6d6,
      fins: true,
      living: 0.4,
    },
    windowStyle: 'curtain',
    glass: glass({ tint: 0x21455e, lit: 0.72, blinds: 0.12 }),
    cornice: 'parapet',
    canopy: 'glow',
    addition: { floors: 4, style: 'lattice', inset: 0.9, tint: 0x54739c },
    roof: roof({ solar: 8, garden: 8, holo: true, pad: true, vents: 2, bulkhead: true }),
    storefronts: [
      {
        name: 'ONE VINE',
        sub: 'MIXED-USE VERTICAL DISTRICT',
        type: 'lobbyFuture',
        signKind: 'holo',
        awning: 'glow',
        color: 0x0c1526,
        accent: 0x8fd7ff,
        extras: ['podSeats', 'planterModern', 'inductionPad'],
        width: 0.62,
      },
      {
        name: 'PRINT-A-PART',
        sub: 'FAB ON DEMAND  •  4 MIN',
        type: 'fabShop',
        signKind: 'holo',
        awning: 'glow',
        color: 0x1a1030,
        accent: 0xff7ae0,
        extras: ['fabGlow', 'holoMenu', 'lockerWall'],
        width: 0.38,
      },
    ],
    wallSign: {
      kind: 'holo',
      side: 'front-upper',
      text: 'ASCEND',
      sub: 'ORBITAL DAY TRIPS — BOOK NEURALLY',
      bg: 0x0a0f28,
      fg: 0xc08cff,
      wear: 0,
    },
  },
};

// ---------------------------------------------------------------------------
// LOT D — tenement, demolished 1998, rebuilt 2019
// ---------------------------------------------------------------------------
const D = {
  '1945': {
    kind: 'building',
    label: 'Tenement (1889) — tailor & shoe repair',
    floors: 4,
    floorH: 3.2,
    groundH: 4.2,
    facade: { tex: 'brick', color: 0x77452f, trim: 0xb5a892, base: 'brick', grime: 0.55 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x262a30, lit: 0.3, blinds: 0.25, curtains: 0.75, flowerBox: 0.35 }),
    cornice: 'bracketed',
    fireEscape: true,
    laundryLines: true,
    roof: roof({ tanks: 1, antennas: 1, vents: 2, pigeons: 4 }),
    storefronts: [
      {
        name: 'TAILOR',
        sub: 'ALTERATIONS  •  PRESSING',
        type: 'tailor',
        signKind: 'painted',
        awning: 'canvas-stripe',
        color: 0x3a2b1e,
        accent: 0xe4d6b8,
        extras: ['sewingWindow', 'barberPole', 'milkCrates'],
        width: 0.5,
      },
      {
        name: 'SHOE REPAIR',
        sub: 'WHILE-U-WAIT',
        type: 'cobbler',
        signKind: 'painted',
        awning: null,
        color: 0x1f3326,
        accent: 0xdccfae,
        extras: ['sandwichBoard'],
        width: 0.5,
      },
    ],
    wallSign: null,
  },
  '1965': {
    kind: 'building',
    label: 'Tenement — TV & Hi-Fi showroom',
    floors: 4,
    floorH: 3.2,
    groundH: 4.2,
    facade: { tex: 'brick', color: 0x7f4d36, trim: 0xbfb39d, base: 'brick', grime: 0.44 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x323b45, lit: 0.36, blinds: 0.3, curtains: 0.6 }),
    cornice: 'bracketed',
    fireEscape: true,
    roof: roof({ tanks: 1, antennas: 6, vents: 2 }),
    storefronts: [
      {
        name: 'TV & HI-FI',
        sub: 'COLOR SETS  •  STEREO CONSOLES',
        type: 'tvShop',
        signKind: 'plastic',
        awning: 'metal',
        color: 0x9c1f1f,
        accent: 0xf6e7a1,
        extras: ['tvWall', 'starburst', 'newsRack'],
        width: 1.0,
      },
    ],
    wallSign: null,
  },
  '1985': {
    kind: 'building',
    label: 'Tenement — arcade & pizza slice window',
    floors: 4,
    floorH: 3.2,
    groundH: 4.2,
    facade: { tex: 'brick', color: 0x5f3a2b, trim: 0x8d8375, base: 'brick', grime: 0.9 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x1b1f24, lit: 0.42, blinds: 0.3, ac: 0.7, boarded: 0.3, bars: 0.25 }),
    cornice: 'bracketed',
    fireEscape: true,
    roof: roof({ tanks: 1, antennas: 3, dishes: 1, ac: 3, vents: 3 }),
    storefronts: [
      {
        name: 'SLICE',
        sub: '99¢  •  OPEN TILL 3AM',
        type: 'pizza',
        signKind: 'neon',
        awning: null,
        color: 0x2b1414,
        accent: 0xff5a2d,
        extras: ['sliceCounter', 'graffitiTag', 'drumTrash'],
        width: 0.52,
      },
      {
        name: 'GAME ROOM',
        sub: 'TOKENS  •  PINBALL',
        type: 'arcade',
        signKind: 'neon',
        awning: null,
        color: 0x120d29,
        accent: 0xa855ff,
        extras: ['arcadeGlow', 'posterWall', 'boardedWindow'],
        width: 0.48,
      },
    ],
    wallSign: {
      kind: 'graffiti',
      side: 'east',
      text: 'RIOT',
      sub: 'TFK',
      bg: 0x6b4232,
      fg: 0x39ff88,
      wear: 0.35,
    },
  },
  '2005': {
    kind: 'lot',
    label: 'Surface parking — tenement demolished 1998',
    fence: 'chainlink',
    billboard: {
      kind: 'billboard-lit',
      w: 8.4,
      h: 3.4,
      text: 'BROADBAND',
      sub: 'UNLIMITED DIAL-FREE INTERNET  •  1-800-555-0199',
      bg: 0x0b2f6b,
      fg: 0xf2f7ff,
      accent: 0xffb703,
    },
    contents: ['parkedCars', 'lightPole', 'payKiosk', 'weeds', 'stripes', 'dumpster'],
    partyWall: { west: true, east: true, tex: 'brick', color: 0x6b4130, ghost: true },
  },
  '2025': {
    kind: 'building',
    label: 'The Vine — 2019 CLT mixed-use infill',
    floors: 6,
    floorH: 3.1,
    groundH: 4.4,
    facade: { tex: 'timber', color: 0xb99263, trim: 0x2f3134, base: 'concrete', grime: 0.08 },
    windowStyle: 'bay',
    glass: glass({ tint: 0x33424e, lit: 0.7, blinds: 0.2, flowerBox: 0.55 }),
    cornice: 'flat',
    balconies: true,
    roof: roof({ ac: 1, solar: 5, garden: 4, vents: 1, bulkhead: true }),
    storefronts: [
      {
        name: 'BOBA LAB',
        sub: 'BROWN SUGAR  •  OAT  •  0% SUGAR',
        type: 'boba',
        signKind: 'minimal',
        awning: 'canvas-flat',
        color: 0x2a1b2e,
        accent: 0xffc2e2,
        extras: ['queueRope', 'sidewalkTables', 'deliveryBags', 'chalkboard'],
        width: 0.55,
      },
      {
        name: 'REPAIR',
        sub: 'SCREENS  •  BATTERIES  •  30 MIN',
        type: 'repair',
        signKind: 'minimal',
        awning: null,
        color: 0x14202b,
        accent: 0x63d2ff,
        extras: ['windowDecals', 'scooterPair'],
        width: 0.45,
      },
    ],
    wallSign: {
      kind: 'mural',
      side: 'east',
      text: 'GROW',
      sub: 'COMMUNITY MURAL 2022',
      bg: 0x243b6b,
      fg: 0xffd166,
      wear: 0.05,
    },
  },
  '2055': {
    kind: 'building',
    label: 'The Vine — drone-serviced, farm-topped',
    floors: 6,
    floorH: 3.1,
    groundH: 4.4,
    facade: { tex: 'timber', color: 0xa2825b, trim: 0x23262b, base: 'concrete', grime: 0.1, living: 0.6 },
    windowStyle: 'bay',
    glass: glass({ tint: 0x2b3d55, lit: 0.75, blinds: 0.1 }),
    cornice: 'flat',
    balconies: true,
    roof: roof({ solar: 6, garden: 9, pad: true, holo: false, vents: 1, bulkhead: true }),
    storefronts: [
      {
        name: 'SYNTH RAMEN',
        sub: 'CULTURED BROTH  •  90 SEC',
        type: 'ramen',
        signKind: 'holo',
        awning: 'glow',
        color: 0x20101c,
        accent: 0xff5f7e,
        extras: ['podSeats', 'holoMenu', 'lockerWall'],
        width: 0.55,
      },
      {
        name: 'MED-POD',
        sub: 'DIAGNOSTIC  •  WALK-IN',
        type: 'medpod',
        signKind: 'holo',
        awning: 'glow',
        color: 0x0d1d24,
        accent: 0x7cffd4,
        extras: ['medGlow', 'inductionPad'],
        width: 0.45,
      },
    ],
    wallSign: {
      kind: 'holo',
      side: 'east',
      text: 'GROW',
      sub: 'MURAL 2022 — AUGMENTED 2051',
      bg: 0x10203a,
      fg: 0x9fe8a0,
      wear: 0,
    },
  },
};

// ---------------------------------------------------------------------------
// LOT E — brick, hidden under a mid-century slipcover, revealed again in 2005
// ---------------------------------------------------------------------------
const E = {
  '1945': {
    kind: 'building',
    label: 'Ostrander Building (1897) — apothecary',
    floors: 3,
    floorH: 3.7,
    groundH: 4.8,
    facade: { tex: 'brick', color: 0x9a5b41, trim: 0xcfc3ac, base: 'stone', grime: 0.38 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x2a2f37, lit: 0.24, blinds: 0.4, curtains: 0.5 }),
    cornice: 'bracketed',
    pilasters: true,
    fireEscape: false,
    roof: roof({ tanks: 1, antennas: 1, vents: 2, pigeons: 2 }),
    storefronts: [
      {
        name: 'APOTHECARY',
        sub: 'DRUGS  •  SUNDRIES  •  TOBACCO',
        type: 'apothecary',
        signKind: 'gilded',
        awning: 'canvas-stripe',
        color: 0x1e2f3a,
        accent: 0xd9b45a,
        extras: ['mortarPestle', 'transomStained', 'cigarStand', 'sidewalkClock'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'painted',
      side: 'east',
      text: 'BREAD',
      sub: 'BAKED FRESH DAILY — 12¢',
      bg: 0x7a5c23,
      fg: 0xf5e9cc,
      wear: 0.3,
    },
  },
  '1965': {
    kind: 'building',
    label: 'Ostrander Building — 1958 metal slipcover',
    floors: 3,
    floorH: 3.7,
    groundH: 4.8,
    facade: { tex: 'brick', color: 0x9a5b41, trim: 0xcfc3ac, base: 'panel', grime: 0.2 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x333c46, lit: 0.3, blinds: 0.5 }),
    cornice: 'flat',
    slipcover: { color: 0x7fd0c4, tex: 'porcelain', pattern: 'grid', coverFrom: 1 },
    roof: roof({ tanks: 1, antennas: 4, vents: 2, ac: 1 }),
    storefronts: [
      {
        name: 'LAUNDROMAT',
        sub: 'WASH 20¢  •  DRY 10¢  •  OPEN 24 HRS',
        type: 'laundromat',
        signKind: 'plastic',
        awning: null,
        color: 0x0e5aa8,
        accent: 0xfff3c4,
        extras: ['washerRow', 'starburst', 'gumballMachine'],
        width: 1.0,
      },
    ],
    wallSign: {
      kind: 'ghost',
      side: 'east',
      text: 'BREAD',
      sub: 'BAKED FRESH DAILY — 12¢',
      bg: 0x7a5c23,
      fg: 0xf5e9cc,
      wear: 0.75,
    },
  },
  '1985': {
    kind: 'building',
    label: 'Ostrander Building — slipcover failing',
    floors: 3,
    floorH: 3.7,
    groundH: 4.8,
    facade: { tex: 'brick', color: 0x7d4a35, trim: 0x998f80, base: 'panel', grime: 0.85 },
    windowStyle: 'punched',
    glass: glass({ tint: 0x1d2126, lit: 0.4, blinds: 0.35, ac: 0.5, boarded: 0.2 }),
    cornice: 'flat',
    slipcover: { color: 0x5c8f88, tex: 'porcelain', pattern: 'grid', coverFrom: 1, damage: 0.55 },
    roof: roof({ tanks: 1, antennas: 2, dishes: 1, ac: 2, vents: 3 }),
    storefronts: [
      {
        name: 'TAN & NAILS',
        sub: '10 SESSIONS $29',
        type: 'tanning',
        signKind: 'neon',
        awning: null,
        color: 0x2d1533,
        accent: 0xff8ad8,
        extras: ['neonScript', 'posterWall', 'graffitiTag'],
        width: 0.5,
      },
      {
        name: 'COMICS',
        sub: 'BACK ISSUES  •  D&D  •  CARDS',
        type: 'comics',
        signKind: 'plastic',
        awning: null,
        color: 0x14224a,
        accent: 0xffd23f,
        extras: ['posterWall', 'securityGrille', 'newsBoxes'],
        width: 0.5,
      },
    ],
    wallSign: {
      kind: 'graffiti',
      side: 'east',
      text: 'FADE',
      sub: 'ONE',
      bg: 0x6d4331,
      fg: 0x63e0ff,
      wear: 0.4,
    },
  },
  '2005': {
    kind: 'building',
    label: 'Ostrander Building — 2002 slipcover removal',
    floors: 3,
    floorH: 3.7,
    groundH: 4.8,
    facade: { tex: 'brick', color: 0x94573e, trim: 0xc0b6a4, base: 'stone', grime: 0.42 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x2b333c, lit: 0.5, blinds: 0.4, ac: 0.25 }),
    cornice: 'bracketed',
    pilasters: true,
    roof: roof({ tanks: 1, antennas: 1, dishes: 2, ac: 2, vents: 2 }),
    storefronts: [
      {
        name: 'SUSHI',
        sub: 'LUNCH SPECIAL $8.95',
        type: 'sushi',
        signKind: 'vinyl',
        awning: 'canvas-flat',
        color: 0x1b1b1f,
        accent: 0xd94f45,
        extras: ['noren', 'menuCase', 'binPair'],
        width: 0.5,
      },
      {
        name: 'COPY & PRINT',
        sub: 'FAX  •  SCAN  •  PASSPORT PHOTO',
        type: 'copyShop',
        signKind: 'vinyl',
        awning: null,
        color: 0xf0f2f4,
        accent: 0x1f6fb8,
        extras: ['windowDecals', 'aFrameSign'],
        width: 0.5,
      },
    ],
    wallSign: null,
  },
  '2025': {
    kind: 'building',
    label: 'Ostrander Building — mural-wrapped',
    floors: 3,
    floorH: 3.7,
    groundH: 4.8,
    facade: { tex: 'brick', color: 0x9e5f44, trim: 0xcdc3b2, base: 'stone', grime: 0.26 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x36414d, lit: 0.62, blinds: 0.25, flowerBox: 0.3 }),
    cornice: 'bracketed',
    pilasters: true,
    roof: roof({ tanks: 1, ac: 2, solar: 3, garden: 3, vents: 2 }),
    storefronts: [
      {
        name: 'BARBER',
        sub: 'WALK-INS  •  FADES  •  BEARD',
        type: 'barber',
        signKind: 'minimal',
        awning: null,
        color: 0x101418,
        accent: 0xe6e1d6,
        extras: ['barberPole', 'benchOutside', 'planterRow'],
        width: 0.48,
      },
      {
        name: 'CLIMB CO',
        sub: 'BOULDER  •  YOGA  •  SAUNA',
        type: 'gym',
        signKind: 'minimal',
        awning: null,
        color: 0x1c2b26,
        accent: 0x9ef07a,
        extras: ['windowDecals', 'bikeLeaning', 'scooterPair'],
        width: 0.52,
      },
    ],
    wallSign: {
      kind: 'mural',
      side: 'east',
      text: 'BREAD',
      sub: 'GHOST SIGN RESTORED 2018',
      bg: 0x7a5c23,
      fg: 0xf5e9cc,
      wear: 0.45,
    },
  },
  '2055': {
    kind: 'building',
    label: 'Ostrander Building — augmented heritage frontage',
    floors: 3,
    floorH: 3.7,
    groundH: 4.8,
    facade: { tex: 'brick', color: 0x8d5540, trim: 0xb8b0a2, base: 'stone', grime: 0.3, living: 0.3 },
    windowStyle: 'arched',
    glass: glass({ tint: 0x2b3a52, lit: 0.7, blinds: 0.12 }),
    cornice: 'bracketed',
    pilasters: true,
    roof: roof({ solar: 4, garden: 5, holo: true, vents: 1 }),
    storefronts: [
      {
        name: 'ATELIER',
        sub: 'BESPOKE FABRICATION  •  BIO-DYE',
        type: 'atelier',
        signKind: 'holo',
        awning: 'glow',
        color: 0x171226,
        accent: 0xc9a6ff,
        extras: ['holoMenu', 'podSeats'],
        width: 0.48,
      },
      {
        name: 'AQUA GYM',
        sub: 'NEURO-CALIBRATED TRAINING',
        type: 'gymFuture',
        signKind: 'holo',
        awning: 'glow',
        color: 0x0e2230,
        accent: 0x62e8ff,
        extras: ['medGlow', 'inductionPad', 'scooterPair'],
        width: 0.52,
      },
    ],
    wallSign: null,
  },
};

// ---------------------------------------------------------------------------
// LOT F — corner service station → convenience → EV plaza → autonomy hub
// ---------------------------------------------------------------------------
const F = {
  '1945': {
    kind: 'gas',
    label: 'Vine & 4th Service Station — Sinclair-era',
    style: '1945',
    kiosk: { w: 6.4, d: 6.0, h: 3.6, color: 0xe8e4d8, trim: 0x2c5f4a, roof: 'hip' },
    canopy: { w: 11, d: 7.5, h: 4.2, color: 0xe8e4d8, trim: 0x2c5f4a, posts: 2 },
    pumps: { count: 2, style: 'visible', color: 0xb03a2e },
    pylon: { h: 6.2, text: 'SERVICE', sub: 'GAS 21¢', bg: 0x2c5f4a, fg: 0xf3ead2, kind: 'painted' },
    extras: ['oilRack', 'tyreStack', 'airHose', 'bay', 'bucket', 'attendant'],
    wallSign: null,
  },
  '1965': {
    kind: 'gas',
    label: 'Vine & 4th — full-serve, three islands',
    style: '1965',
    kiosk: { w: 7.2, d: 6.4, h: 3.4, color: 0xf2f0e8, trim: 0xc0392b, roof: 'flat-fold' },
    canopy: { w: 14, d: 8.5, h: 4.6, color: 0xf5f3ea, trim: 0xc0392b, posts: 3 },
    pumps: { count: 4, style: 'boxy', color: 0xf0efe6 },
    pylon: { h: 9.0, text: 'GAS', sub: '31.9¢ / GAL', bg: 0xc0392b, fg: 0xfff6d8, kind: 'plastic' },
    extras: ['oilRack', 'tyreStack', 'airHose', 'bay', 'vendingMachine', 'attendant', 'bunting'],
    wallSign: null,
  },
  '1985': {
    kind: 'gas',
    label: 'Vine & 4th — self-serve mini mart',
    style: '1985',
    kiosk: { w: 8.6, d: 7.0, h: 3.6, color: 0xd8cfbc, trim: 0x1f6f5c, roof: 'mansard' },
    canopy: { w: 12.5, d: 8.0, h: 4.6, color: 0xd9d2c2, trim: 0x1f6f5c, posts: 2 },
    pumps: { count: 4, style: 'digital', color: 0xd6d2c6 },
    pylon: { h: 8.0, text: 'MINI MART', sub: 'SELF SERVE  •  1.09⁹', bg: 0x1f6f5c, fg: 0xffe14d, kind: 'plastic-lit' },
    extras: ['iceBox', 'propaneCage', 'airHose', 'vendingMachine', 'drumTrash', 'graffitiTag', 'payphone'],
    wallSign: null,
  },
  '2005': {
    kind: 'gas',
    label: 'Vine & 4th — branded convenience store',
    style: '2005',
    kiosk: { w: 9.4, d: 7.4, h: 3.8, color: 0xf3f4f6, trim: 0x1f4f9c, roof: 'flat' },
    canopy: { w: 14.5, d: 9.0, h: 5.0, color: 0xf6f7f9, trim: 0x1f4f9c, posts: 2, lit: true },
    pumps: { count: 6, style: 'modern', color: 0xeceef1 },
    pylon: { h: 8.6, text: 'FUEL', sub: 'REGULAR 2.19⁹  •  CAR WASH', bg: 0x1f4f9c, fg: 0xffffff, kind: 'led-price' },
    extras: ['iceBox', 'propaneCage', 'airHose', 'atm', 'binPair', 'squeegee', 'carWashSign'],
    wallSign: null,
  },
  '2025': {
    kind: 'plaza',
    label: 'Vine & 4th Charge Plaza — 2021 conversion',
    style: '2025',
    kiosk: { w: 7.0, d: 5.4, h: 3.4, color: 0x2a3138, trim: 0x5ecf9a, roof: 'green' },
    canopy: { w: 15, d: 10, h: 4.8, color: 0x3a4147, trim: 0x5ecf9a, posts: 3, solar: true },
    chargers: { count: 6, color: 0xe9edf0, accent: 0x5ecf9a },
    pylon: { h: 7.2, text: 'CHARGE', sub: '350 kW  •  12 MIN  •  CAFE', bg: 0x14211c, fg: 0x5ecf9a, kind: 'led' },
    extras: ['cafePod', 'planterRow', 'bikeRepairStand', 'scooterDock', 'sidewalkTables', 'raingarden'],
    wallSign: null,
  },
  '2055': {
    kind: 'plaza',
    label: 'Vine & 4th Autonomy Hub — pod dock & drone port',
    style: '2055',
    kiosk: { w: 6.6, d: 5.2, h: 3.6, color: 0x18203a, trim: 0x8f7bff, roof: 'green' },
    canopy: { w: 16, d: 11, h: 5.6, color: 0x1d2540, trim: 0x8f7bff, posts: 2, solar: true, glow: true },
    chargers: { count: 4, color: 0x2a3352, accent: 0x8f7bff, induction: true },
    pylon: { h: 8.4, text: 'AUTONOMY', sub: 'POD DOCK 12  •  DRONE PORT  •  LEVEL 5', bg: 0x0d1230, fg: 0x9f8cff, kind: 'holo' },
    extras: ['podDock', 'droneTower', 'planterRow', 'growRacks', 'holoBollards', 'raingarden', 'lockerWall'],
    wallSign: null,
  },
};

export const LOT_HISTORY = { A, B, C, D, E, F };

/**
 * The south side of the street: a shallower row of backdrop buildings, plus a
 * distant skyline. Cheaper to build, still era-specific.
 */
export const SOUTH_ROW = {
  '1945': [
    { w: 12, floors: 4, tex: 'brick', color: 0x81503c, cornice: 'simple', sign: 'HOTEL VINE', signKind: 'painted', fireEscape: true },
    { w: 9, floors: 3, tex: 'brick', color: 0x6f4634, cornice: 'bracketed', sign: 'HARDWARE', signKind: 'painted' },
    { w: 11, floors: 5, tex: 'stone', color: 0xb0a897, cornice: 'heavy', sign: 'OFFICES', signKind: 'gilded' },
    { w: 14, floors: 3, tex: 'brick', color: 0x76483a, cornice: 'simple', sign: 'THEATRE', signKind: 'marquee' },
    { w: 10, floors: 2, tex: 'brick', color: 0x8d5943, cornice: 'simple', sign: 'FEED & GRAIN', signKind: 'painted' },
    { w: 8, floors: 3, tex: 'brick', color: 0x8a5943, cornice: 'simple', sign: 'BARBER', signKind: 'painted' },
  ],
  '1965': [
    { w: 12, floors: 4, tex: 'brick', color: 0x8a5842, cornice: 'simple', sign: 'HOTEL VINE', signKind: 'plastic', fireEscape: true },
    { w: 9, floors: 3, tex: 'panel', color: 0xd8cfa8, cornice: 'flat', sign: 'HARDWARE', signKind: 'plastic' },
    { w: 11, floors: 5, tex: 'stone', color: 0xbab2a1, cornice: 'heavy', sign: 'INSURANCE', signKind: 'enamel' },
    { w: 14, floors: 3, tex: 'brick', color: 0x7d4f3f, cornice: 'simple', sign: 'CINEMA', signKind: 'marquee' },
    { w: 10, floors: 3, tex: 'panel', color: 0xa9d8d0, cornice: 'flat', sign: 'CAFETERIA', signKind: 'plastic' },
    { w: 8, floors: 3, tex: 'panel', color: 0xe8d8a8, cornice: 'flat', sign: 'BOWLING', signKind: 'plastic' },
  ],
  '1985': [
    { w: 12, floors: 4, tex: 'brick', color: 0x6b4536, cornice: 'simple', sign: 'ROOMS $19', signKind: 'neon', fireEscape: true },
    { w: 9, floors: 3, tex: 'panel', color: 0xa89b7c, cornice: 'flat', sign: 'LIQUOR', signKind: 'neon' },
    { w: 11, floors: 5, tex: 'stone', color: 0x958d7d, cornice: 'heavy', sign: 'FOR LEASE', signKind: 'plastic' },
    { w: 14, floors: 3, tex: 'brick', color: 0x66423a, cornice: 'simple', sign: 'TRIPLE X', signKind: 'marquee-neon' },
    { w: 10, floors: 3, tex: 'panel', color: 0x7e9c96, cornice: 'flat', sign: 'CHECKS', signKind: 'neon' },
    { w: 8, floors: 3, tex: 'panel', color: 0xa89b8c, cornice: 'flat', sign: 'ARCADE', signKind: 'neon' },
  ],
  '2005': [
    { w: 12, floors: 4, tex: 'brick', color: 0x7d5142, cornice: 'simple', sign: 'LOFTS', signKind: 'vinyl', fireEscape: true },
    { w: 9, floors: 3, tex: 'panel', color: 0xcfc9bb, cornice: 'flat', sign: 'BANK', signKind: 'vinyl' },
    { w: 11, floors: 6, tex: 'curtain', color: 0x93a6b2, cornice: 'parapet', sign: 'MEDICAL', signKind: 'vinyl' },
    { w: 14, floors: 3, tex: 'brick', color: 0x77503f, cornice: 'simple', sign: 'CINEMA 4', signKind: 'marquee' },
    { w: 10, floors: 3, tex: 'panel', color: 0xbcc7c4, cornice: 'flat', sign: 'DELI', signKind: 'vinyl' },
    { w: 8, floors: 3, tex: 'panel', color: 0xc8cec9, cornice: 'flat', sign: 'FITNESS', signKind: 'vinyl' },
  ],
  '2025': [
    { w: 12, floors: 5, tex: 'brick', color: 0x89594a, cornice: 'simple', sign: 'THE VINE LOFTS', signKind: 'minimal', fireEscape: true },
    { w: 9, floors: 4, tex: 'timber', color: 0xb08f61, cornice: 'flat', sign: 'CO-WORK', signKind: 'minimal' },
    { w: 11, floors: 7, tex: 'curtain', color: 0x8397a5, cornice: 'parapet', sign: 'CLINIC', signKind: 'minimal' },
    { w: 14, floors: 3, tex: 'brick', color: 0x7f5645, cornice: 'simple', sign: 'CINEMA', signKind: 'marquee-led' },
    { w: 10, floors: 4, tex: 'panel', color: 0xb9c3c0, cornice: 'flat', sign: 'MARKET HALL', signKind: 'minimal' },
    { w: 8, floors: 4, tex: 'timber', color: 0xa8895e, cornice: 'flat', sign: 'CLIMB', signKind: 'minimal' },
  ],
  '2055': [
    { w: 12, floors: 6, tex: 'brick', color: 0x7b5346, cornice: 'simple', sign: 'VINE HABITAT', signKind: 'holo', living: 0.5 },
    { w: 9, floors: 5, tex: 'timber', color: 0x9c7f57, cornice: 'flat', sign: 'MAKERS', signKind: 'holo', living: 0.3 },
    { w: 11, floors: 9, tex: 'curtain', color: 0x6d8093, cornice: 'parapet', sign: 'CARE', signKind: 'holo' },
    { w: 14, floors: 4, tex: 'brick', color: 0x6f4c41, cornice: 'simple', sign: 'IMMERSE', signKind: 'marquee-holo' },
    { w: 10, floors: 5, tex: 'panel', color: 0x9fb0ae, cornice: 'flat', sign: 'FOOD FAB', signKind: 'holo', living: 0.4 },
    { w: 8, floors: 5, tex: 'panel', color: 0x8fa0a8, cornice: 'flat', sign: 'VOLUME', signKind: 'holo', living: 0.3 },
  ],
};

/**
 * The south side is split either side of a 12 m gap at x ∈ [-6, 6] — a pocket
 * park that survives all six eras in different states of care. It also gives
 * the camera a corridor to pull back through.
 */
export const SOUTH_LAYOUT = {
  westStart: -40,
  gap: [-6.5, 6.5],
  eastStart: 6.5,
  westCount: 3,
};

export const POCKET_PARK = {
  '1945': { rail: 'iron', trees: 0.75, grass: 0x5f6b3a, monument: 'obelisk', bench: 'timber', litter: 0.3, lamp: true, extra: 'bandstand' },
  '1965': { rail: 'iron', trees: 0.85, grass: 0x6b7a3f, monument: 'fountain', bench: 'timber', litter: 0.15, lamp: true, extra: 'sandpit' },
  '1985': { rail: 'chain', trees: 0.95, grass: 0x4f5a33, monument: 'fountain-dry', bench: 'broken', litter: 0.9, lamp: true, extra: 'graffiti' },
  '2005': { rail: 'steel', trees: 1.0, grass: 0x5a6b3a, monument: 'fountain', bench: 'metal', litter: 0.3, lamp: true, extra: 'playground' },
  '2025': { rail: 'none', trees: 1.05, grass: 0x5f7a42, monument: 'fountain', bench: 'metal', litter: 0.15, lamp: true, extra: 'raingarden' },
  '2055': { rail: 'none', trees: 1.15, grass: 0x527a4a, monument: 'holo-art', bench: 'glow', litter: 0.05, lamp: true, extra: 'canopy' },
};

/** Distant skyline silhouette profile per era: [x, width, height] triples. */
export const SKYLINE = {
  '1945': { maxH: 34, count: 22, style: 'lowrise' },
  '1965': { maxH: 52, count: 26, style: 'modern' },
  '1985': { maxH: 62, count: 28, style: 'boxy' },
  '2005': { maxH: 78, count: 30, style: 'glass' },
  '2025': { maxH: 96, count: 32, style: 'glass' },
  '2055': { maxH: 150, count: 36, style: 'future' },
};
