/**
 * Era definitions.
 *
 * Every visual, audible and behavioural aspect of the city block is derived
 * from these records. Adding a new era is (almost) a matter of adding a record
 * here plus a lot-history column in ./block.js
 */

export const ERAS = [
  {
    id: '1945',
    year: 1945,
    name: 'Post-War',
    subtitle: 'Victory on Vine Street',
    palette: '#c9a26b',
    blurb:
      'Bunting still hangs from the bank cornice. Streetcar 41 grinds along Vine Street, ' +
      'the corner service station pumps 21¢ gasoline, and every sign on the block was ' +
      'painted by hand on a ladder.',
    details: [
      'Streetcar + overhead trolley wire down the centre of the street',
      'Hand-lettered signage, canvas awnings, painted brick wall ads',
      'Cast-iron lamp posts with incandescent globes',
      'Fedoras, trench coats, seamed stockings, newsboy on the corner',
      'Fire escapes, water towers, coal smoke haze',
    ],
    // ---- atmosphere -------------------------------------------------------
    timeOfDay: 'late afternoon',
    sky: {
      top: 0x6f9dc4,
      mid: 0xbcc7c0,
      bottom: 0xe6c795,
      sunDir: [-0.62, 0.34, 0.71],
      sunColor: 0xffd39a,
      sunSize: 0.03,
      haze: 0.62,
      stars: 0,
      clouds: { amount: 0.4, color: 0xf2dfc0, speed: 0.4 },
    },
    light: {
      sun: 2.5,
      sunColor: 0xffd7a6,
      skyColor: 0xa8c4e0,
      groundColor: 0x7d6248,
      hemi: 0.62,
      ambient: 0.16,
      ambientColor: 0xc0a884,
      shadow: 0.9,
    },
    fog: { color: 0xd6bd97, density: 0.0072 },
    grade: {
      exposure: 1.02,
      saturation: 0.66,
      contrast: 1.1,
      lift: 0.012,
      tint: [1.07, 1.0, 0.84],
      grain: 0.13,
      vignette: 0.52,
      bloom: 0.28,
      bloomThreshold: 0.82,
      chroma: 0.0,
      scan: 0.0,
    },
    weather: { kind: 'dust', amount: 0.35, wet: 0.0 },
    // ---- streetscape ------------------------------------------------------
    street: {
      surface: 'cobble',
      markings: 'none',
      tracks: true,
      trolleyWire: true,
      bikeLane: false,
      lightStrip: false,
      crosswalk: 'none',
      curb: 'granite',
      sidewalk: 'slab-worn',
      hydrant: 'victorian',
      lamp: 'iron-globe',
      poles: 'wood',
      signal: 'pedestal',
      mailbox: 'olive',
      trash: 'ashcan',
      phone: 'none',
      meters: false,
      busStop: 'sign-old',
      planters: false,
      bikeRack: false,
      scooters: false,
      evCharger: false,
      parklet: false,
      dumpster: false,
      newsstand: true,
      graffiti: 0.0,
      litter: 0.35,
      treeStage: 0.18,
      skybridge: false,
      dronePad: false,
    },
    signStyle: 'painted',
    adStyle: 'painted',
    // ---- population -------------------------------------------------------
    traffic: {
      density: 0.55,
      speed: 7.5,
      kinds: ['sedan45', 'sedan45', 'taxi45', 'panel45', 'pickup45', 'coupe45'],
      tram: 'streetcar',
      bus: null,
      bikes: 0.2,
      flying: 0,
    },
    crowd: {
      density: 0.85,
      speed: 1.25,
      outfits: ['suit45', 'dress45', 'worker45', 'sailor45', 'newsboy45', 'coat45'],
      props: ['briefcase', 'newspaper', 'hatbox', 'none', 'none'],
    },
    audio: {
      bed: { rumble: 0.22, hiss: 0.3, crowd: 0.22, hum: 0.0, wind: 0.25 },
      music: 'swing',
      events: ['tramBell', 'oldHorn', 'whistle', 'radio', 'paperboy'],
      lowpass: 2600,
    },
  },

  {
    id: '1965',
    year: 1965,
    name: 'Mid-Century',
    subtitle: 'Progress on Schedule',
    palette: '#5fb0c8',
    blurb:
      'The vacant lot is gone — nine floors of aluminium and green glass now call ' +
      'themselves the Progress Building. Chrome fins glitter at the curb, the streetcar ' +
      'rails are paved over, and every second storefront wears a backlit plastic sign.',
    details: [
      'Streetcar rails paved over — buses and finned V8s take the street',
      'Backlit plastic and porcelain-enamel signage, starburst motifs',
      'A metal "slipcover" facade hides the old brick on Lot E',
      'Cobra-head street lights, parking meters, glass phone booth',
      'TV aerials sprouting from every roof',
    ],
    timeOfDay: 'midday',
    sky: {
      top: 0x2f74c8,
      mid: 0x84b6e6,
      bottom: 0xd6e7f4,
      sunDir: [0.28, 0.78, 0.56],
      sunColor: 0xfff6df,
      sunSize: 0.024,
      haze: 0.3,
      stars: 0,
      clouds: { amount: 0.28, color: 0xffffff, speed: 0.5 },
    },
    light: {
      sun: 3.35,
      sunColor: 0xfff4e0,
      skyColor: 0xbcd8ff,
      groundColor: 0x8d8a7e,
      hemi: 0.7,
      ambient: 0.14,
      ambientColor: 0xd8e6ff,
      shadow: 1.0,
    },
    fog: { color: 0xc9dcee, density: 0.0042 },
    grade: {
      exposure: 1.06,
      saturation: 1.16,
      contrast: 1.08,
      lift: 0.006,
      tint: [1.02, 1.0, 1.02],
      grain: 0.06,
      vignette: 0.36,
      bloom: 0.3,
      bloomThreshold: 0.86,
      chroma: 0.0,
      scan: 0.0,
    },
    weather: { kind: 'clear', amount: 0.0, wet: 0.0 },
    street: {
      surface: 'asphalt-new',
      markings: 'classic',
      tracks: 'paved',
      trolleyWire: false,
      bikeLane: false,
      lightStrip: false,
      crosswalk: 'ladder',
      curb: 'concrete',
      sidewalk: 'slab',
      hydrant: 'classic',
      lamp: 'cobra',
      poles: 'wood',
      signal: 'mast-old',
      mailbox: 'blue',
      trash: 'wire',
      phone: 'booth',
      meters: true,
      busStop: 'sign-mid',
      planters: false,
      bikeRack: false,
      scooters: false,
      evCharger: false,
      parklet: false,
      dumpster: false,
      newsstand: true,
      graffiti: 0.0,
      litter: 0.15,
      treeStage: 0.42,
      skybridge: false,
      dronePad: false,
    },
    signStyle: 'plastic',
    adStyle: 'billboard',
    traffic: {
      density: 0.8,
      speed: 10.5,
      kinds: ['fin65', 'fin65', 'wagon65', 'muscle65', 'van65', 'taxi65'],
      tram: null,
      bus: 'bus65',
      bikes: 0.15,
      flying: 0,
    },
    crowd: {
      density: 0.95,
      speed: 1.35,
      outfits: ['mod65', 'suit65', 'housewife65', 'teen65', 'worker65', 'kid65'],
      props: ['shoppingBag', 'briefcase', 'none', 'none', 'camera'],
    },
    audio: {
      bed: { rumble: 0.38, hiss: 0.14, crowd: 0.26, hum: 0.05, wind: 0.16 },
      music: 'surf',
      events: ['v8Pass', 'chromeHorn', 'busAir', 'transistorRadio', 'jackhammer'],
      lowpass: 6500,
    },
  },

  {
    id: '1985',
    year: 1985,
    name: 'Neon Decline',
    subtitle: 'Two Bucks a Night, Be Kind Rewind',
    palette: '#e0509a',
    blurb:
      'Sodium light, spray paint and burnt-out bulbs. The arcade bleeps through a propped ' +
      'door, the bank has become a cheque-cashing window, and the Progress Building has ' +
      'gone the colour of weak coffee.',
    details: [
      'Dusk lighting — neon, sodium vapour and backlit plastic carry the scene',
      'Graffiti tags, barred windows, boarded transoms, dumpsters',
      'Window air-conditioners, satellite dish on the tower roof',
      'Payphones, newspaper honour boxes, ad-wrapped bus shelter',
      'Windbreakers, big hair, boomboxes, skateboards',
    ],
    timeOfDay: 'dusk',
    sky: {
      top: 0x18213f,
      mid: 0x5a4570,
      bottom: 0xe0763f,
      sunDir: [0.74, 0.09, -0.66],
      sunColor: 0xff9040,
      sunSize: 0.042,
      haze: 0.68,
      stars: 0.25,
      clouds: { amount: 0.5, color: 0xb1749a, speed: 0.3 },
    },
    light: {
      sun: 1.15,
      sunColor: 0xff9a52,
      skyColor: 0x4a5a86,
      groundColor: 0x3a2f30,
      hemi: 0.38,
      ambient: 0.13,
      ambientColor: 0x6a5878,
      shadow: 0.55,
    },
    fog: { color: 0x2f2a42, density: 0.0102 },
    grade: {
      exposure: 1.08,
      saturation: 1.1,
      contrast: 1.16,
      lift: 0.014,
      tint: [1.04, 0.97, 1.06],
      grain: 0.15,
      vignette: 0.62,
      bloom: 0.5,
      bloomThreshold: 0.74,
      chroma: 0.0012,
      scan: 0.05,
    },
    weather: { kind: 'smog', amount: 0.5, wet: 0.18 },
    street: {
      surface: 'asphalt-patched',
      markings: 'worn',
      tracks: 'ghost',
      trolleyWire: false,
      bikeLane: false,
      lightStrip: false,
      crosswalk: 'ladder-worn',
      curb: 'concrete-broken',
      sidewalk: 'slab-cracked',
      hydrant: 'classic',
      lamp: 'sodium',
      poles: 'wood',
      signal: 'mast',
      mailbox: 'blue',
      trash: 'drum',
      phone: 'payphone',
      meters: true,
      busStop: 'shelter-ad',
      planters: false,
      bikeRack: false,
      scooters: false,
      evCharger: false,
      parklet: false,
      dumpster: true,
      newsstand: false,
      graffiti: 0.85,
      litter: 0.8,
      treeStage: 0.72,
      skybridge: false,
      dronePad: false,
    },
    signStyle: 'neon',
    adStyle: 'billboard-lit',
    traffic: {
      density: 0.7,
      speed: 9.5,
      kinds: ['box85', 'box85', 'hatch85', 'wagon85', 'taxi85', 'van85'],
      tram: null,
      bus: 'bus85',
      bikes: 0.2,
      flying: 0,
    },
    crowd: {
      density: 0.8,
      speed: 1.3,
      outfits: ['windbreaker85', 'punk85', 'suit85', 'aerobics85', 'jean85', 'cop85'],
      props: ['boombox', 'skateboard', 'none', 'shoppingBag', 'none'],
    },
    audio: {
      bed: { rumble: 0.34, hiss: 0.2, crowd: 0.2, hum: 0.22, wind: 0.2 },
      music: 'synth',
      events: ['arcade', 'carAlarm', 'sirenFar', 'bassCar', 'payphone'],
      lowpass: 9000,
    },
  },

  {
    id: '2005',
    year: 2005,
    name: 'Turn of the Century',
    subtitle: 'Now With Free Wi-Fi',
    palette: '#8fa3b8',
    blurb:
      'Grey drizzle, silver cars and a glass recladding. The tenement on Lot D is a parking ' +
      'lot now, its blank flank rented out to a broadband billboard. Everything is beige, ' +
      'brushed aluminium, and slightly damp.',
    details: [
      'Overcast drizzle, wet asphalt reflections',
      'Lot D demolished — surface parking behind chain link',
      'Blue-green glass recladding on the Progress Building',
      'Corporate vinyl signage, scaffolding, bike racks, planters',
      'Bootcut jeans, cargo shorts, flip phones, wired earbuds',
    ],
    timeOfDay: 'overcast morning',
    sky: {
      top: 0x8a99a8,
      mid: 0xa9b5c0,
      bottom: 0xc3ccd4,
      sunDir: [-0.3, 0.62, -0.72],
      sunColor: 0xdfe6ec,
      sunSize: 0.0,
      haze: 0.85,
      stars: 0,
      clouds: { amount: 0.95, color: 0x9fa9b4, speed: 0.7 },
    },
    light: {
      sun: 1.05,
      sunColor: 0xd8e2ee,
      skyColor: 0xc4cfda,
      groundColor: 0x6f7378,
      hemi: 1.05,
      ambient: 0.2,
      ambientColor: 0xb8c2cc,
      shadow: 0.24,
    },
    fog: { color: 0xa9b4bf, density: 0.0105 },
    grade: {
      exposure: 1.0,
      saturation: 0.78,
      contrast: 1.04,
      lift: 0.014,
      tint: [0.97, 1.0, 1.05],
      grain: 0.05,
      vignette: 0.42,
      bloom: 0.22,
      bloomThreshold: 0.9,
      chroma: 0.0,
      scan: 0.0,
    },
    weather: { kind: 'rain', amount: 0.7, wet: 0.85 },
    street: {
      surface: 'asphalt',
      markings: 'modern',
      tracks: false,
      trolleyWire: false,
      bikeLane: false,
      lightStrip: false,
      crosswalk: 'ladder',
      curb: 'concrete',
      sidewalk: 'slab',
      hydrant: 'modern',
      lamp: 'shoebox',
      poles: 'concrete',
      signal: 'mast',
      mailbox: 'blue',
      trash: 'bin',
      phone: 'payphone-slim',
      meters: true,
      busStop: 'shelter-glass',
      planters: true,
      bikeRack: true,
      scooters: false,
      evCharger: false,
      parklet: false,
      dumpster: true,
      newsstand: false,
      graffiti: 0.2,
      litter: 0.3,
      treeStage: 0.9,
      skybridge: false,
      dronePad: false,
    },
    signStyle: 'vinyl',
    adStyle: 'billboard-lit',
    traffic: {
      density: 0.95,
      speed: 9.0,
      kinds: ['suv05', 'sedan05', 'sedan05', 'minivan05', 'taxi05', 'van05'],
      tram: null,
      bus: 'bus05',
      bikes: 0.25,
      flying: 0,
    },
    crowd: {
      density: 0.9,
      speed: 1.35,
      outfits: ['office05', 'baggy05', 'hoodie05', 'suit05', 'student05', 'jogger05'],
      props: ['coffee', 'flipPhone', 'backpack', 'umbrella', 'umbrella'],
    },
    audio: {
      bed: { rumble: 0.4, hiss: 0.42, crowd: 0.24, hum: 0.16, wind: 0.22 },
      music: 'indie',
      events: ['ringtone', 'busAir', 'skid', 'trolleyBagRoll', 'construction'],
      lowpass: 11000,
    },
  },

  {
    id: '2025',
    year: 2025,
    name: 'Present Day',
    subtitle: 'Delivered in 12 Minutes',
    palette: '#5ecf9a',
    blurb:
      'Golden hour, mass timber and a media wall. Lot D is a six-storey mixed-use block, ' +
      'the service station is an EV plaza under solar canopies, and the kerb belongs to ' +
      'e-bikes, scooters and outdoor dining.',
    details: [
      'Protected bike lane, e-scooter dock, parklet dining sheds',
      'Animated LED media wall + painted mural art',
      'EV charging plaza with solar canopy on the corner',
      'Cross-laminated timber mixed-use infill on Lot D',
      'Puffers, athleisure, earbuds, cargo bikes, delivery couriers',
    ],
    timeOfDay: 'golden hour',
    sky: {
      top: 0x3f7ac4,
      mid: 0x9ec2df,
      bottom: 0xf6cf9a,
      sunDir: [0.72, 0.22, 0.66],
      sunColor: 0xffd9a4,
      sunSize: 0.03,
      haze: 0.4,
      stars: 0,
      clouds: { amount: 0.42, color: 0xffe4c4, speed: 0.45 },
    },
    light: {
      sun: 3.0,
      sunColor: 0xffcf96,
      skyColor: 0xa6c8ea,
      groundColor: 0x74705f,
      hemi: 0.72,
      ambient: 0.15,
      ambientColor: 0xcfdcea,
      shadow: 0.85,
    },
    fog: { color: 0xc9d3dd, density: 0.005 },
    grade: {
      exposure: 1.05,
      saturation: 1.06,
      contrast: 1.08,
      lift: 0.008,
      tint: [1.03, 1.0, 0.98],
      grain: 0.035,
      vignette: 0.4,
      bloom: 0.42,
      bloomThreshold: 0.8,
      chroma: 0.0004,
      scan: 0.0,
    },
    weather: { kind: 'clear', amount: 0.12, wet: 0.05 },
    street: {
      surface: 'asphalt',
      markings: 'modern',
      tracks: false,
      trolleyWire: false,
      bikeLane: true,
      lightStrip: false,
      crosswalk: 'continental',
      curb: 'concrete',
      sidewalk: 'slab-new',
      hydrant: 'modern',
      lamp: 'led-arm',
      poles: 'concrete',
      signal: 'mast-led',
      mailbox: 'blue',
      trash: 'bin-solar',
      phone: 'none',
      meters: 'kiosk',
      busStop: 'shelter-solar',
      planters: true,
      bikeRack: true,
      scooters: true,
      evCharger: true,
      parklet: true,
      dumpster: true,
      newsstand: false,
      graffiti: 0.25,
      litter: 0.2,
      treeStage: 1.0,
      skybridge: false,
      dronePad: false,
    },
    signStyle: 'minimal',
    adStyle: 'led',
    traffic: {
      density: 0.85,
      speed: 8.5,
      kinds: ['ev25', 'suv25', 'sedan25', 'cargoVan25', 'rideshare25', 'ev25'],
      tram: null,
      bus: 'bus25',
      bikes: 0.75,
      flying: 0.15,
    },
    crowd: {
      density: 1.0,
      speed: 1.35,
      outfits: ['puffer25', 'athleisure25', 'tech25', 'courier25', 'student25', 'parent25'],
      props: ['phone', 'phone', 'coffee', 'tote', 'yogaMat'],
    },
    audio: {
      bed: { rumble: 0.3, hiss: 0.24, crowd: 0.3, hum: 0.2, wind: 0.2 },
      music: 'lofi',
      events: ['evWhine', 'scooterBell', 'notification', 'busAir', 'skate'],
      lowpass: 14000,
    },
  },

  {
    id: '2055',
    year: 2055,
    name: 'Near Future',
    subtitle: 'Kerbside Reserved for Autonomy',
    palette: '#8f7bff',
    blurb:
      'Blue hour under a living facade. Traffic runs on lit guideways, freight arrives by ' +
      'drone, and the 1912 bank shell survives beneath a glass hat with a heritage hologram ' +
      'bolted to its cornice.',
    details: [
      'Roadway markings replaced by embedded light guideways',
      'Volumetric holographic advertising, no printed billboards',
      'Vertical farm racks and living facades on three lots',
      'Autonomous pods, hover freight, rooftop drone pads, skybridge',
      'Techwear with electroluminescent trim, visors, companion drones',
    ],
    timeOfDay: 'blue hour',
    sky: {
      top: 0x090f2a,
      mid: 0x1d2a5c,
      bottom: 0x4a4d86,
      sunDir: [-0.7, 0.06, -0.71],
      sunColor: 0x9a7cff,
      sunSize: 0.0,
      haze: 0.55,
      stars: 0.85,
      clouds: { amount: 0.35, color: 0x3c4480, speed: 0.25 },
    },
    light: {
      sun: 0.5,
      sunColor: 0x9fb4ff,
      skyColor: 0x33407e,
      groundColor: 0x1b2036,
      hemi: 0.42,
      ambient: 0.16,
      ambientColor: 0x5060a8,
      shadow: 0.3,
    },
    fog: { color: 0x161c3a, density: 0.0115 },
    grade: {
      exposure: 1.12,
      saturation: 1.12,
      contrast: 1.14,
      lift: 0.018,
      tint: [0.97, 0.99, 1.09],
      grain: 0.05,
      vignette: 0.6,
      bloom: 0.62,
      bloomThreshold: 0.68,
      chroma: 0.0018,
      scan: 0.03,
    },
    weather: { kind: 'fog', amount: 0.6, wet: 0.4 },
    street: {
      surface: 'composite',
      markings: 'none',
      tracks: false,
      trolleyWire: false,
      bikeLane: true,
      lightStrip: true,
      crosswalk: 'lightstrip',
      curb: 'composite',
      sidewalk: 'composite',
      hydrant: 'flush',
      lamp: 'halo',
      poles: 'none',
      signal: 'holo',
      mailbox: 'locker',
      trash: 'chute',
      phone: 'none',
      meters: false,
      busStop: 'podDock',
      planters: true,
      bikeRack: true,
      scooters: true,
      evCharger: 'induction',
      parklet: true,
      dumpster: false,
      newsstand: false,
      graffiti: 0.18,
      litter: 0.05,
      treeStage: 1.15,
      skybridge: true,
      dronePad: true,
    },
    signStyle: 'holo',
    adStyle: 'holo',
    traffic: {
      density: 0.8,
      speed: 12.0,
      kinds: ['pod55', 'pod55', 'shuttle55', 'freight55', 'pod55', 'trike55'],
      tram: null,
      bus: 'shuttle55',
      bikes: 0.5,
      flying: 1.0,
    },
    crowd: {
      density: 0.9,
      speed: 1.4,
      outfits: ['techwear55', 'techwear55', 'lumen55', 'medic55', 'exo55', 'kid55'],
      props: ['companionDrone', 'holoSlate', 'none', 'companionDrone', 'holoSlate'],
    },
    audio: {
      bed: { rumble: 0.14, hiss: 0.12, crowd: 0.18, hum: 0.5, wind: 0.3 },
      music: 'ambient',
      events: ['droneWhir', 'podPass', 'holoChime', 'servo', 'transitAnnounce'],
      lowpass: 16000,
    },
  },
];

export const ERA_BY_ID = Object.fromEntries(ERAS.map((e) => [e.id, e]));
export const ERA_IDS = ERAS.map((e) => e.id);
export const ERA_YEARS = ERAS.map((e) => e.year);

export function eraIndexOf(id) {
  return ERA_IDS.indexOf(id);
}
